export const USER_STATE_CHANGE = "USER_STATE_CHANGE";

export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const USER_POSTS_DATA_STATE_CHANGE = "USER_POSTS_DATA_STATE_CHANGE";

export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE";
export const USER_FOLLOWING_DATA_STATE_CHANGE = "USER_FOLLOWING_DATA_STATE_CHANGE";

export const USERS_STATE_CHANGE = "USERS_STATE_CHANGE";
export const USERS_DATA_STATE_CHANGE = "USERS_DATA_STATE_CHANGE";

export const USERS_POSTS_STATE_CHANGE = "USERS_POSTS_STATE_CHANGE";
export const USERS_POSTS_DATA_STATE_CHANGE = "USERS_POSTS_DATA_STATE_CHANGE";
export const UPDATE_POSTS = "UPDATE_POSTS";

export const USERS_STORY_STATE_CHANGE = "USERS_STORY_STATE_CHANGE";
export const USERS_STORY_DATA_STATE_CHANGE = "USERS_STORY_DATA_STATE_CHANGE";

export const USERS_STORY_BY_UUID_STATE_CHANGE = "USERS_STORY_BY_UUID_STATE_CHANGE";
export const USERS_STORY_BY_UUID_DATA_STATE_CHANGE = "USERS_STORY_BY_UUID_DATA_STATE_CHANGE";

export const USERS_CHAT_LIST_STATE_CHANGE = "USERS_CHAT_LIST_STATE_CHANGE";
export const USERS_CHAT_LIST_DATA_STATE_CHANGE = "USERS_CHAT_LIST_DATA_STATE_CHANGE";

export const NOTIFICATIONS_STATE_CHANGE = "NOTIFICATIONS_STATE_CHANGE";
export const NOTIFICATIONS_DATA_STATE_CHANGE = "NOTIFICATIONS_DATA_STATE_CHANGE";

export const USER_SHORTVIDEOS_STATE_CHANGE = "USER_SHORTVIDEOS_STATE_CHANGE";
export const USER_SHORTVIDEOS_DATA_STATE_CHANGE = "USER_SHORTVIDEOS_DATA_STATE_CHANGE";


export const USER_SAVEDPOSTS_STATE_CHANGE = "USER_SAVEDPOSTS_STATE_CHANGE";
export const USER_SAVEDPOSTS_DATA_STATE_CHANGE = "USER_SAVEDPOSTS_DATA_STATE_CHANGE";

export const USER_FOLLOWERS_STATE_CHANGE = "USER_FOLLOWERS_STATE_CHANGE";
export const USER_FOLLOWERS_DATA_STATE_CHANGE = "USER_FOLLOWERS_DATA_STATE_CHANGE";

export const USER_FRIENDS_STATE_CHANGE = "USER_FRIENDS_STATE_CHANGE";
export const USER_FRIENDS_DATA_STATE_CHANGE = "USER_FRIENDS_DATA_STATE_CHANGE";


export const CLEAR_DATA = "CLEAR_DATA";



